services:

  postgres_db:
    container_name: postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trans_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - content:/app/avatars

  client:
    container_name: client
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./client:/usr/share/nginx/html/

  cli_client:
    container_name: cli_client
    build:
      context: ./CLI_client
      dockerfile: Dockerfile
    image: cli_client
    restart: on-failure:3

volumes:
  postgres-data:
  content:


