services:

  postgres_db:
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trans_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"

  # client:
  #   image: nginx:alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./client:/usr/share/nginx/html/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_db

volumes:
  postgres-data:
