services:

  postgres_db:
    container_name: postgres
    image: postgres
    hostname: localhost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trans_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - content:/app/avatars
    networks:
      - backend

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nginx_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/share/nginx/html/

  cli_client:
    container_name: cli_client
    build:
      context: ./CLI_client
      dockerfile: Dockerfile
    image: cli_client
    restart: on-failure:3
    networks:
      - backend

volumes:
  postgres-data:
  content:



networks:
  backend:
