services:

  postgres_db:
    container_name: postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trans_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - content:/app/avatars

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nginx_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/share/nginx/html/

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres_db

volumes:
  postgres-data:
  content:


