version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/index.html:/usr/share/nginx/html/index.html
      - ./src/style.css:/usr/share/nginx/html/style.css
